### PR TITLE
PowerShell example, script

### PR DESCRIPTION
**Pull request by luncliff**
### Changes

Add a sample script for PowerShell users with a short description. The work is based on bash.md.

### Tested with ...

Mac environment, PowerShell Core 7.1.3

### CODE REVIEW

**Comment by YoungjaeKim** [comment]
Sorry for the late review. I'm testing the code, and some logics are giving wrong output. For example, `2018-12-31` date should give `1901` not `1852` as yearweek. 
This is because, the logic you've written does not follow ISO 8601. I'm testing and fixing for better recommendation.

**Comment by luncliff** [comment]
@YoungjaeKim Appreciate the review. I will take a look for those edge cases within days.

**Comment by luncliff** [comment]
Compared the output using https://myweb.ecu.edu/mccartyr/isowdcal.html.

#### 2018-2019

* `2018-12-30` -> 2018-W52
* `2018-12-31` -> 2019-W01
* `2019-01-06` -> 2019-W01

#### 2019-2020

* `2019-12-29` -> 2019-W52
* `2019-12-30` -> 2020-W01
* `2020-01-05` -> 2020-W01


#### 2020-2021

* `2020-12-28` -> 2020-W53
* `2021-01-03` -> 2020-W53
* `2021-01-04` -> 2021-W01

**Comment by YoungjaeKim** [comment]
Thanks. I've validated with my test table which I've updated at the tail of Readme; https://github.com/line/headver#validation 
Your code now gives `{yearweek}` results correctly. Thanks.

**Pull request merged**
